name: Test JS Functions and Notify Slack

on: 
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install 

      - name: Run tests
        run: npm test

      - name: Notify Slack
        if: always()  # Run even if tests fail
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C077F0UFSJG'
          slack-message: |
            Test Results for Node ${{ matrix.node-version }}:
            ${{ job.status }}
            ```
            Sorry. Using this for testing purposes. Ignore
            ${{ steps.test.outputs.summary }}
            ```
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

